/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Referral {
  export type ReferralStatsStruct = {
    totalReferrals: BigNumberish;
    successfulReferrals: BigNumberish;
  };

  export type ReferralStatsStructOutput = [
    totalReferrals: bigint,
    successfulReferrals: bigint
  ] & { totalReferrals: bigint; successfulReferrals: bigint };
}

export interface ReferralInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "codeToReferrer"
      | "completeReferral"
      | "createReferral"
      | "getReferralStats"
      | "leaderboard"
      | "owner"
      | "referrerToCode"
      | "renounceOwnership"
      | "rewardAmount"
      | "rewardToken"
      | "stats"
      | "transferOwnership"
      | "userToReferrer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReferralCompleted"
      | "ReferralRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "codeToReferrer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "completeReferral",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createReferral",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "leaderboard",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "referrerToCode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "stats", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userToReferrer",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "codeToReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referrerToCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userToReferrer",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralCompletedEvent {
  export type InputTuple = [
    referrer: AddressLike,
    user: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [referrer: string, user: string, reward: bigint];
  export interface OutputObject {
    referrer: string;
    user: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRegisteredEvent {
  export type InputTuple = [referrer: AddressLike, code: string];
  export type OutputTuple = [referrer: string, code: string];
  export interface OutputObject {
    referrer: string;
    code: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Referral extends BaseContract {
  connect(runner?: ContractRunner | null): Referral;
  waitForDeployment(): Promise<this>;

  interface: ReferralInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  codeToReferrer: TypedContractMethod<[arg0: string], [string], "view">;

  completeReferral: TypedContractMethod<[code: string], [void], "nonpayable">;

  createReferral: TypedContractMethod<[code: string], [void], "nonpayable">;

  getReferralStats: TypedContractMethod<
    [referrer: AddressLike],
    [Referral.ReferralStatsStructOutput],
    "view"
  >;

  leaderboard: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  referrerToCode: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardAmount: TypedContractMethod<[], [bigint], "view">;

  rewardToken: TypedContractMethod<[], [string], "view">;

  stats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint] & { totalReferrals: bigint; successfulReferrals: bigint }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userToReferrer: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "codeToReferrer"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "completeReferral"
  ): TypedContractMethod<[code: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createReferral"
  ): TypedContractMethod<[code: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getReferralStats"
  ): TypedContractMethod<
    [referrer: AddressLike],
    [Referral.ReferralStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "leaderboard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referrerToCode"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint] & { totalReferrals: bigint; successfulReferrals: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userToReferrer"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReferralCompleted"
  ): TypedContractEvent<
    ReferralCompletedEvent.InputTuple,
    ReferralCompletedEvent.OutputTuple,
    ReferralCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRegistered"
  ): TypedContractEvent<
    ReferralRegisteredEvent.InputTuple,
    ReferralRegisteredEvent.OutputTuple,
    ReferralRegisteredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReferralCompleted(address,address,uint256)": TypedContractEvent<
      ReferralCompletedEvent.InputTuple,
      ReferralCompletedEvent.OutputTuple,
      ReferralCompletedEvent.OutputObject
    >;
    ReferralCompleted: TypedContractEvent<
      ReferralCompletedEvent.InputTuple,
      ReferralCompletedEvent.OutputTuple,
      ReferralCompletedEvent.OutputObject
    >;

    "ReferralRegistered(address,string)": TypedContractEvent<
      ReferralRegisteredEvent.InputTuple,
      ReferralRegisteredEvent.OutputTuple,
      ReferralRegisteredEvent.OutputObject
    >;
    ReferralRegistered: TypedContractEvent<
      ReferralRegisteredEvent.InputTuple,
      ReferralRegisteredEvent.OutputTuple,
      ReferralRegisteredEvent.OutputObject
    >;
  };
}
