/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as buyStablesPortalSol from "./BuyStablesPortal.sol";
export type { buyStablesPortalSol };
export type { MockRouter } from "./MockRouter";
