/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILaunchpadCore,
  ILaunchpadCoreInterface,
} from "../../../../contracts/market/Marketplace.sol/ILaunchpadCore";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "purchaseId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "splitAndTransferVestingSchedule",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "purchaseId",
        type: "uint256",
      },
    ],
    name: "transferVestingSchedule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILaunchpadCore__factory {
  static readonly abi = _abi;
  static createInterface(): ILaunchpadCoreInterface {
    return new Interface(_abi) as ILaunchpadCoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILaunchpadCore {
    return new Contract(address, _abi, runner) as unknown as ILaunchpadCore;
  }
}
