/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LaunchpadCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CLIFF_DURATION"
      | "MINT_FEE_BPS"
      | "VESTING_DURATION"
      | "claimVested"
      | "convertToMP"
      | "forfeitPurchase"
      | "getUserPurchases"
      | "ltToken"
      | "marketplaceAddress"
      | "mpToken"
      | "owner"
      | "paymentToken"
      | "purchaseCounter"
      | "purchaseTokens"
      | "purchases"
      | "renounceOwnership"
      | "setMarketplaceAddress"
      | "splitAndTransferVestingSchedule"
      | "tokenPrice"
      | "transferOwnership"
      | "transferVestingSchedule"
      | "treasury"
      | "userPurchases"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ForfeitureExecuted"
      | "MintingCostPaid"
      | "OwnershipTransferred"
      | "TokensConvertedToMP"
      | "TokensPurchased"
      | "VestedTokensClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CLIFF_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINT_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VESTING_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimVested",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "convertToMP",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forfeitPurchase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPurchases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "ltToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "marketplaceAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mpToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchases",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketplaceAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "splitAndTransferVestingSchedule",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferVestingSchedule",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userPurchases",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CLIFF_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINT_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VESTING_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimVested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "convertToMP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forfeitPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ltToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketplaceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mpToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "purchases", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketplaceAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "splitAndTransferVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userPurchases",
    data: BytesLike
  ): Result;
}

export namespace ForfeitureExecutedEvent {
  export type InputTuple = [
    purchaseId: BigNumberish,
    user: AddressLike,
    forfeitedAmount: BigNumberish
  ];
  export type OutputTuple = [
    purchaseId: bigint,
    user: string,
    forfeitedAmount: bigint
  ];
  export interface OutputObject {
    purchaseId: bigint;
    user: string;
    forfeitedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintingCostPaidEvent {
  export type InputTuple = [
    purchaseId: BigNumberish,
    user: AddressLike,
    feeAmount: BigNumberish
  ];
  export type OutputTuple = [
    purchaseId: bigint,
    user: string,
    feeAmount: bigint
  ];
  export interface OutputObject {
    purchaseId: bigint;
    user: string;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensConvertedToMPEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    purchaseId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [purchaseId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    purchaseId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestedTokensClaimedEvent {
  export type InputTuple = [
    purchaseId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [purchaseId: bigint, user: string, amount: bigint];
  export interface OutputObject {
    purchaseId: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LaunchpadCore extends BaseContract {
  connect(runner?: ContractRunner | null): LaunchpadCore;
  waitForDeployment(): Promise<this>;

  interface: LaunchpadCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CLIFF_DURATION: TypedContractMethod<[], [bigint], "view">;

  MINT_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  VESTING_DURATION: TypedContractMethod<[], [bigint], "view">;

  claimVested: TypedContractMethod<
    [purchaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  convertToMP: TypedContractMethod<
    [amountLT: BigNumberish],
    [void],
    "nonpayable"
  >;

  forfeitPurchase: TypedContractMethod<
    [purchaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getUserPurchases: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  ltToken: TypedContractMethod<[], [string], "view">;

  marketplaceAddress: TypedContractMethod<[], [string], "view">;

  mpToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  purchaseCounter: TypedContractMethod<[], [bigint], "view">;

  purchaseTokens: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  purchases: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        user: string;
        amountLT: bigint;
        claimedAmount: bigint;
        purchaseTime: bigint;
        cliffEnd: bigint;
        vestingEnd: bigint;
        phase: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMarketplaceAddress: TypedContractMethod<
    [_marketplace: AddressLike],
    [void],
    "nonpayable"
  >;

  splitAndTransferVestingSchedule: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      purchaseId: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  tokenPrice: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferVestingSchedule: TypedContractMethod<
    [from: AddressLike, to: AddressLike, purchaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  userPurchases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CLIFF_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MINT_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VESTING_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimVested"
  ): TypedContractMethod<[purchaseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "convertToMP"
  ): TypedContractMethod<[amountLT: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forfeitPurchase"
  ): TypedContractMethod<[purchaseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getUserPurchases"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "ltToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "marketplaceAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mpToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "purchaseTokens"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "purchases"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {
        user: string;
        amountLT: bigint;
        claimedAmount: bigint;
        purchaseTime: bigint;
        cliffEnd: bigint;
        vestingEnd: bigint;
        phase: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketplaceAddress"
  ): TypedContractMethod<[_marketplace: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "splitAndTransferVestingSchedule"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      purchaseId: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferVestingSchedule"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, purchaseId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userPurchases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ForfeitureExecuted"
  ): TypedContractEvent<
    ForfeitureExecutedEvent.InputTuple,
    ForfeitureExecutedEvent.OutputTuple,
    ForfeitureExecutedEvent.OutputObject
  >;
  getEvent(
    key: "MintingCostPaid"
  ): TypedContractEvent<
    MintingCostPaidEvent.InputTuple,
    MintingCostPaidEvent.OutputTuple,
    MintingCostPaidEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokensConvertedToMP"
  ): TypedContractEvent<
    TokensConvertedToMPEvent.InputTuple,
    TokensConvertedToMPEvent.OutputTuple,
    TokensConvertedToMPEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "VestedTokensClaimed"
  ): TypedContractEvent<
    VestedTokensClaimedEvent.InputTuple,
    VestedTokensClaimedEvent.OutputTuple,
    VestedTokensClaimedEvent.OutputObject
  >;

  filters: {
    "ForfeitureExecuted(uint256,address,uint256)": TypedContractEvent<
      ForfeitureExecutedEvent.InputTuple,
      ForfeitureExecutedEvent.OutputTuple,
      ForfeitureExecutedEvent.OutputObject
    >;
    ForfeitureExecuted: TypedContractEvent<
      ForfeitureExecutedEvent.InputTuple,
      ForfeitureExecutedEvent.OutputTuple,
      ForfeitureExecutedEvent.OutputObject
    >;

    "MintingCostPaid(uint256,address,uint256)": TypedContractEvent<
      MintingCostPaidEvent.InputTuple,
      MintingCostPaidEvent.OutputTuple,
      MintingCostPaidEvent.OutputObject
    >;
    MintingCostPaid: TypedContractEvent<
      MintingCostPaidEvent.InputTuple,
      MintingCostPaidEvent.OutputTuple,
      MintingCostPaidEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokensConvertedToMP(address,uint256)": TypedContractEvent<
      TokensConvertedToMPEvent.InputTuple,
      TokensConvertedToMPEvent.OutputTuple,
      TokensConvertedToMPEvent.OutputObject
    >;
    TokensConvertedToMP: TypedContractEvent<
      TokensConvertedToMPEvent.InputTuple,
      TokensConvertedToMPEvent.OutputTuple,
      TokensConvertedToMPEvent.OutputObject
    >;

    "TokensPurchased(uint256,address,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "VestedTokensClaimed(uint256,address,uint256)": TypedContractEvent<
      VestedTokensClaimedEvent.InputTuple,
      VestedTokensClaimedEvent.OutputTuple,
      VestedTokensClaimedEvent.OutputObject
    >;
    VestedTokensClaimed: TypedContractEvent<
      VestedTokensClaimedEvent.InputTuple,
      VestedTokensClaimedEvent.OutputTuple,
      VestedTokensClaimedEvent.OutputObject
    >;
  };
}
