/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace SXUA {
  export type SubAccountStruct = {
    id: BigNumberish;
    committedAmount: BigNumberish;
    uncommittedAmount: BigNumberish;
    depositTime: BigNumberish;
    lastYieldAccrual: BigNumberish;
    depositToken: AddressLike;
  };

  export type SubAccountStructOutput = [
    id: bigint,
    committedAmount: bigint,
    uncommittedAmount: bigint,
    depositTime: bigint,
    lastYieldAccrual: bigint,
    depositToken: string
  ] & {
    id: bigint;
    committedAmount: bigint;
    uncommittedAmount: bigint;
    depositTime: bigint;
    lastYieldAccrual: bigint;
    depositToken: string;
  };
}

export interface SXUAInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAILY_YIELD_BPS"
      | "EARLY_WITHDRAWAL_PENALTY_BPS"
      | "LOCK_DURATION"
      | "accrueYield"
      | "addSupportedStable"
      | "depositWithSplit"
      | "depositWithSplitFor"
      | "getBalances"
      | "getSubAccounts"
      | "owner"
      | "ptfFeeAddress"
      | "ptfFeeBps"
      | "removeSupportedStable"
      | "renounceOwnership"
      | "stableDecimals"
      | "supportedStables"
      | "sxmmAddress"
      | "sxpToken"
      | "transferOwnership"
      | "userSubAccounts"
      | "withdraw"
      | "withdrawalFeeAddress"
      | "withdrawalFeeBps"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "OwnershipTransferred"
      | "PTFCollected"
      | "PenaltyApplied"
      | "Withdrawn"
      | "YieldAccrued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DAILY_YIELD_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EARLY_WITHDRAWAL_PENALTY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accrueYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupportedStable",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithSplit",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithSplitFor",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubAccounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ptfFeeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ptfFeeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeSupportedStable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stableDecimals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedStables",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sxmmAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "sxpToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userSubAccounts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalFeeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalFeeBps",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DAILY_YIELD_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EARLY_WITHDRAWAL_PENALTY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accrueYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addSupportedStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositWithSplit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositWithSplitFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ptfFeeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ptfFeeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedStable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stableDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedStables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sxmmAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sxpToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSubAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalFeeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalFeeBps",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    subAccountId: BigNumberish,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    user: string,
    subAccountId: bigint,
    amount: bigint,
    token: string
  ];
  export interface OutputObject {
    user: string;
    subAccountId: bigint;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PTFCollectedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PenaltyAppliedEvent {
  export type InputTuple = [
    user: AddressLike,
    subAccountId: BigNumberish,
    penaltyAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    subAccountId: bigint,
    penaltyAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    subAccountId: bigint;
    penaltyAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    subAccountId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    subAccountId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    user: string;
    subAccountId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldAccruedEvent {
  export type InputTuple = [
    user: AddressLike,
    subAccountId: BigNumberish,
    yieldAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    subAccountId: bigint,
    yieldAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    subAccountId: bigint;
    yieldAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SXUA extends BaseContract {
  connect(runner?: ContractRunner | null): SXUA;
  waitForDeployment(): Promise<this>;

  interface: SXUAInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAILY_YIELD_BPS: TypedContractMethod<[], [bigint], "view">;

  EARLY_WITHDRAWAL_PENALTY_BPS: TypedContractMethod<[], [bigint], "view">;

  LOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  accrueYield: TypedContractMethod<
    [subAccountIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  addSupportedStable: TypedContractMethod<
    [token: AddressLike, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositWithSplit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, committedPercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositWithSplitFor: TypedContractMethod<
    [
      user: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      committedPercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getBalances: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { totalCommitted: bigint; totalUncommitted: bigint }],
    "view"
  >;

  getSubAccounts: TypedContractMethod<
    [user: AddressLike],
    [SXUA.SubAccountStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ptfFeeAddress: TypedContractMethod<[], [string], "view">;

  ptfFeeBps: TypedContractMethod<[], [bigint], "view">;

  removeSupportedStable: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  stableDecimals: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  supportedStables: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  sxmmAddress: TypedContractMethod<[], [string], "view">;

  sxpToken: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userSubAccounts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        id: bigint;
        committedAmount: bigint;
        uncommittedAmount: bigint;
        depositTime: bigint;
        lastYieldAccrual: bigint;
        depositToken: string;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<
    [subAccountIndex: BigNumberish, amountNormalized: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawalFeeAddress: TypedContractMethod<[], [string], "view">;

  withdrawalFeeBps: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAILY_YIELD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EARLY_WITHDRAWAL_PENALTY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accrueYield"
  ): TypedContractMethod<[subAccountIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addSupportedStable"
  ): TypedContractMethod<
    [token: AddressLike, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositWithSplit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, committedPercent: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositWithSplitFor"
  ): TypedContractMethod<
    [
      user: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      committedPercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalances"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { totalCommitted: bigint; totalUncommitted: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubAccounts"
  ): TypedContractMethod<
    [user: AddressLike],
    [SXUA.SubAccountStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ptfFeeAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ptfFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeSupportedStable"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stableDecimals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportedStables"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sxmmAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sxpToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userSubAccounts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        id: bigint;
        committedAmount: bigint;
        uncommittedAmount: bigint;
        depositTime: bigint;
        lastYieldAccrual: bigint;
        depositToken: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [subAccountIndex: BigNumberish, amountNormalized: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawalFeeAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawalFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PTFCollected"
  ): TypedContractEvent<
    PTFCollectedEvent.InputTuple,
    PTFCollectedEvent.OutputTuple,
    PTFCollectedEvent.OutputObject
  >;
  getEvent(
    key: "PenaltyApplied"
  ): TypedContractEvent<
    PenaltyAppliedEvent.InputTuple,
    PenaltyAppliedEvent.OutputTuple,
    PenaltyAppliedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "YieldAccrued"
  ): TypedContractEvent<
    YieldAccruedEvent.InputTuple,
    YieldAccruedEvent.OutputTuple,
    YieldAccruedEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256,uint256,address)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PTFCollected(address,uint256)": TypedContractEvent<
      PTFCollectedEvent.InputTuple,
      PTFCollectedEvent.OutputTuple,
      PTFCollectedEvent.OutputObject
    >;
    PTFCollected: TypedContractEvent<
      PTFCollectedEvent.InputTuple,
      PTFCollectedEvent.OutputTuple,
      PTFCollectedEvent.OutputObject
    >;

    "PenaltyApplied(address,uint256,uint256)": TypedContractEvent<
      PenaltyAppliedEvent.InputTuple,
      PenaltyAppliedEvent.OutputTuple,
      PenaltyAppliedEvent.OutputObject
    >;
    PenaltyApplied: TypedContractEvent<
      PenaltyAppliedEvent.InputTuple,
      PenaltyAppliedEvent.OutputTuple,
      PenaltyAppliedEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;

    "YieldAccrued(address,uint256,uint256)": TypedContractEvent<
      YieldAccruedEvent.InputTuple,
      YieldAccruedEvent.OutputTuple,
      YieldAccruedEvent.OutputObject
    >;
    YieldAccrued: TypedContractEvent<
      YieldAccruedEvent.InputTuple,
      YieldAccruedEvent.OutputTuple,
      YieldAccruedEvent.OutputObject
    >;
  };
}
