/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockLeaderboard,
  MockLeaderboardInterface,
} from "../../../contracts/mocks/MockLeaderboard";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "scores",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "points",
        type: "uint256",
      },
    ],
    name: "updateLeaderboard",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610178806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806376dd110f1461003b57806381a745e51461006d575b600080fd5b61005b6100493660046100cf565b60006020819052908152604090205481565b60405190815260200160405180910390f35b61008061007b3660046100f1565b610082565b005b6001600160a01b038216600090815260208190526040812080548392906100aa90849061011b565b90915550505050565b80356001600160a01b03811681146100ca57600080fd5b919050565b6000602082840312156100e157600080fd5b6100ea826100b3565b9392505050565b6000806040838503121561010457600080fd5b61010d836100b3565b946020939093013593505050565b8082018082111561013c57634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220cecef95f69808f4def7e409c3cbc8b181d4ec57467b6d5505fb3ca97c1e88fae64736f6c63430008180033";

type MockLeaderboardConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockLeaderboardConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockLeaderboard__factory extends ContractFactory {
  constructor(...args: MockLeaderboardConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockLeaderboard & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockLeaderboard__factory {
    return super.connect(runner) as MockLeaderboard__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockLeaderboardInterface {
    return new Interface(_abi) as MockLeaderboardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockLeaderboard {
    return new Contract(address, _abi, runner) as unknown as MockLeaderboard;
  }
}
