/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockLaunchpadCore,
  MockLaunchpadCoreInterface,
} from "../../../contracts/mocks/MockLaunchpadCore";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "scheduleIndex",
        type: "uint256",
      },
    ],
    name: "mintSchedule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "scheduleOwners",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "purchaseId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "splitAndTransferVestingSchedule",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "purchaseId",
        type: "uint256",
      },
    ],
    name: "transferVestingSchedule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061037d806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80633bde032a1461005157806356a65922146100975780639d91a8c8146100ac578063ccb535b0146100e8575b600080fd5b61007a61005f366004610243565b6000602081905290815260409020546001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b6100aa6100a5366004610278565b610109565b005b6100aa6100ba3660046102b4565b600090815260208190526040902080546001600160a01b0319166001600160a01b0392909216919091179055565b6100fb6100f63660046102de565b61019f565b60405190815260200161008e565b6000818152602081905260409020546001600160a01b038481169116146101705760405162461bcd60e51b81526020600482015260166024820152752737ba103a34329039b1b432b23ab6329037bbb732b960511b60448201526064015b60405180910390fd5b600090815260208190526040902080546001600160a01b0319166001600160a01b039290921691909117905550565b6000828152602081905260408120546001600160a01b038681169116146102015760405162461bcd60e51b81526020600482015260166024820152752737ba103a34329039b1b432b23ab6329037bbb732b960511b6044820152606401610167565b600061020f846103e8610320565b600081815260208190526040902080546001600160a01b0388166001600160a01b0319909116179055915050949350505050565b60006020828403121561025557600080fd5b5035919050565b80356001600160a01b038116811461027357600080fd5b919050565b60008060006060848603121561028d57600080fd5b6102968461025c565b92506102a46020850161025c565b9150604084013590509250925092565b600080604083850312156102c757600080fd5b6102d08361025c565b946020939093013593505050565b600080600080608085870312156102f457600080fd5b6102fd8561025c565b935061030b6020860161025c565b93969395505050506040820135916060013590565b8082018082111561034157634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220e765e8b50d2d79caba8e9bddd02822589595a31b35738bbde0d7ae8cd70b592a64736f6c63430008180033";

type MockLaunchpadCoreConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockLaunchpadCoreConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockLaunchpadCore__factory extends ContractFactory {
  constructor(...args: MockLaunchpadCoreConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockLaunchpadCore & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockLaunchpadCore__factory {
    return super.connect(runner) as MockLaunchpadCore__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockLaunchpadCoreInterface {
    return new Interface(_abi) as MockLaunchpadCoreInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockLaunchpadCore {
    return new Contract(address, _abi, runner) as unknown as MockLaunchpadCore;
  }
}
