/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BuyStablesPortal__factory } from "./BuyStablesPortal__factory";
export { ISXCP__factory } from "./ISXCP__factory";
