/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ILaunchpadCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "splitAndTransferVestingSchedule"
      | "transferVestingSchedule"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "splitAndTransferVestingSchedule",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferVestingSchedule",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "splitAndTransferVestingSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferVestingSchedule",
    data: BytesLike
  ): Result;
}

export interface ILaunchpadCore extends BaseContract {
  connect(runner?: ContractRunner | null): ILaunchpadCore;
  waitForDeployment(): Promise<this>;

  interface: ILaunchpadCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  splitAndTransferVestingSchedule: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      purchaseId: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  transferVestingSchedule: TypedContractMethod<
    [from: AddressLike, to: AddressLike, purchaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "splitAndTransferVestingSchedule"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      purchaseId: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferVestingSchedule"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, purchaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
