/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DMSVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateDevice"
      | "masterDevices"
      | "owner"
      | "registerMasterDevice"
      | "registerMasterDeviceFor"
      | "renounceOwnership"
      | "transferOwnership"
      | "validateDPoP"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeviceDeactivated"
      | "MasterDeviceRegistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateDevice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "masterDevices",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMasterDevice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMasterDeviceFor",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateDPoP",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "masterDevices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMasterDevice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMasterDeviceFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateDPoP",
    data: BytesLike
  ): Result;
}

export namespace DeviceDeactivatedEvent {
  export type InputTuple = [admin: AddressLike];
  export type OutputTuple = [admin: string];
  export interface OutputObject {
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MasterDeviceRegisteredEvent {
  export type InputTuple = [admin: AddressLike, deviceHash: BytesLike];
  export type OutputTuple = [admin: string, deviceHash: string];
  export interface OutputObject {
    admin: string;
    deviceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DMSVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): DMSVerifier;
  waitForDeployment(): Promise<this>;

  interface: DMSVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateDevice: TypedContractMethod<
    [admin: AddressLike],
    [void],
    "nonpayable"
  >;

  masterDevices: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint] & {
        deviceHash: string;
        isActive: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerMasterDevice: TypedContractMethod<
    [deviceHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerMasterDeviceFor: TypedContractMethod<
    [admin: AddressLike, deviceHash: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validateDPoP: TypedContractMethod<
    [admin: AddressLike, deviceHash: BytesLike, signature: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateDevice"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "masterDevices"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint] & {
        deviceHash: string;
        isActive: boolean;
        registrationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerMasterDevice"
  ): TypedContractMethod<[deviceHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerMasterDeviceFor"
  ): TypedContractMethod<
    [admin: AddressLike, deviceHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validateDPoP"
  ): TypedContractMethod<
    [admin: AddressLike, deviceHash: BytesLike, signature: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "DeviceDeactivated"
  ): TypedContractEvent<
    DeviceDeactivatedEvent.InputTuple,
    DeviceDeactivatedEvent.OutputTuple,
    DeviceDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MasterDeviceRegistered"
  ): TypedContractEvent<
    MasterDeviceRegisteredEvent.InputTuple,
    MasterDeviceRegisteredEvent.OutputTuple,
    MasterDeviceRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DeviceDeactivated(address)": TypedContractEvent<
      DeviceDeactivatedEvent.InputTuple,
      DeviceDeactivatedEvent.OutputTuple,
      DeviceDeactivatedEvent.OutputObject
    >;
    DeviceDeactivated: TypedContractEvent<
      DeviceDeactivatedEvent.InputTuple,
      DeviceDeactivatedEvent.OutputTuple,
      DeviceDeactivatedEvent.OutputObject
    >;

    "MasterDeviceRegistered(address,bytes32)": TypedContractEvent<
      MasterDeviceRegisteredEvent.InputTuple,
      MasterDeviceRegisteredEvent.OutputTuple,
      MasterDeviceRegisteredEvent.OutputObject
    >;
    MasterDeviceRegistered: TypedContractEvent<
      MasterDeviceRegisteredEvent.InputTuple,
      MasterDeviceRegisteredEvent.OutputTuple,
      MasterDeviceRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
